version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  lint:
    desc: Run all linters
    cmds:
      - pre-commit run --all-files

  lint:ansible:
    desc: Lint the Ansible code
    cmds:
      - bash -c 'source .venv/bin/activate && ansible-lint playbook.yml roles/'
      - echo "✅ Ansible code linted"

  lint:shell:
    desc: Lint shell code
    cmds:
      - find . -name "*.sh" -type f -not -path "./.venv/*" | xargs shellcheck -e SC1091
      - echo "✅ Shell scripts linted"

  syntax-check:
    desc: Run syntax check
    cmds:
      - bash -c 'source .venv/bin/activate && ansible-playbook --syntax-check playbook.yml'
      - echo "✅ Syntax check passed"

  molecule-test:
    desc: Run Molecule tests for default scenario, no destroy
    cmds:
      - bash -c 'source .venv/bin/activate && cd roles/sysinit && molecule test'

  molecule-converge:
    desc: Run Molecule converge for development
    cmds:
      - bash -c 'source .venv/bin/activate && cd roles/sysinit && molecule converge'

  molecule-verify:
    desc: Run Molecule verify only
    cmds:
      - bash -c 'source .venv/bin/activate && cd roles/sysinit && molecule verify'

  molecule-destroy:
    desc: Destroy Molecule test instances
    cmds:
      - bash -c 'source .venv/bin/activate && cd roles/sysinit && molecule destroy'

  # Secrets
  scan-secrets:
    desc: Scan for secrets
    cmds:
      - bash -c 'source .venv/bin/activate && detect-secrets scan --baseline .secrets.baseline --force-use-all-plugins'
      - echo "✅ Secrets scanned"

  update-secrets:
    desc: Update secrets baseline
    cmds:
      - git ls-files -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline

  audit-secrets:
    desc: Audit secrets baseline
    cmds:
      - detect-secrets audit .secrets.baseline

  # Utility tasks
  install:deps:
    desc: Install dependencies
    cmds:
      - if ! command -v prettier >/dev/null 2>&1; then echo "⚠️ prettier not found"; exit 1; fi
      - if ! command -v uv >/dev/null 2>&1; then echo "⚠️ uv not found"; exit 1; fi
      - if ! command -v shellcheck >/dev/null 2>&1; then echo -e "⚠️ shellcheck not found"; exit 1; fi
      - |+
        uv venv --clear
        uv pip install -r requirements.txt
        uv pip install -r development.requirements.txt
        bash -c 'source .venv/bin/activate && ansible-galaxy install -r requirements.yml'

  install:hooks:
    desc: Install pre-commit hooks
    cmds:
      - pre-commit install
      - echo "✅ Pre-commit hooks installed"

  # Additional development tasks
  check:
    deps: ['lint', 'syntax-check', 'scan-secrets']
    desc: Run comprehensive checks
    cmds:
      - echo "✅ All checks passed"

  format:
    desc: Format YAML files with prettier
    cmds:
      - |+
        if command -v prettier >/dev/null 2>&1; then
          find . -name "*.yml" -o -name "*.yaml" | grep -v node_modules | grep -v .venv | xargs prettier --write
          echo "✅ YAML files formatted"
        else
          echo "⚠️ prettier not found, run: 'task install:deps'"
        fi

  upgrade-deps:
    desc: Upgrade Python dependencies
    deps: ['install:deps']
    cmds:
      - uv pip install --upgrade pip
      - uv pip install --upgrade -r requirements.txt
      - uv pip install --upgrade -r development.requirements.txt
      - bash -c 'source .venv/bin/activate && ansible-galaxy install --force -r requirements.yml'
      - echo "✅ Dependencies upgraded"
