---
- name: AWS - BMA - Exists
  ansible.builtin.stat:
    path: "/home/{{ lookup('env','USER') }}/.bash-my-aws"
  register: bma_exists_result

- name: AWS - BMA - Install/Upgrade
  become: true
  become_user: "{{ lookup('env','USER') }}"
  when: bma_exists_result.stat.exists == false
  ansible.builtin.git:
    repo: https://github.com/bash-my-aws/bash-my-aws.git
    dest: "/home/{{ lookup('env','USER') }}/.bash-my-aws"
