---
- name: Bash-my-aws - Check if already exists
  ansible.builtin.stat:
    path: "{{ sysinit_user_home }}/.bash-my-aws"
  register: bma_exists_result

- name: Bash-my-aws - Install or upgrade from Git
  become: true
  become_user: "{{ sysinit_user }}"
  when: not bma_exists_result.stat.exists or sysinit_force_update
  ansible.builtin.git:
    repo: https://github.com/bash-my-aws/bash-my-aws.git
    dest: "{{ sysinit_user_home }}/.bash-my-aws"
    version: main
