---
- name: Dropbox - Exists
  ansible.builtin.stat:
    path: /usr/bin/dropbox
  register: dropbox_exists_result

- name: Dropbox - Install/Upgrade
  ansible.builtin.apt:
    deb: https://www.dropbox.com/download?dl=packages/debian/dropbox_2024.01.22_amd64.deb
  when: ansible_distribution == 'Debian' and (not dropbox_exists_result.stat.exists or upgrade)

- name: Dropbox - Install/Upgrade
  ansible.builtin.apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
  when: ansible_distribution == 'Ubuntu' and (not dropbox_exists_result.stat.exists or upgrade)
