---
- name: Fzf - Exists
  ansible.builtin.stat:
    path: ~/.fzf/bin/fzf
  register: fzf_exists_result

- name: Checkout Fzf installer
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: ~/.fzf/
    version: master

- name: Fzf - Install
  ansible.builtin.shell: >
    ~/.fzf/install --xdg --all --no-update-rc
  when: not fzf_exists_result.stat.exists # or upgrade
  changed_when: true
