---
- name: Leapp Exists
  ansible.builtin.stat:
    path: /usr/bin/leapp
  register: leapp_exists_result

- name: Leapp Install
  ansible.builtin.apt:
    deb: "https://asset.noovolari.com/latest/Leapp_{{ leapp_version }}_amd64.deb"
  when: not leapp_exists_result.stat.exists or upgrade
