---
- name: Packer - Exists
  ansible.builtin.stat:
    path: /usr/bin/packer
  register: packer_exists_result

- name: Packer installation block
  when: not packer_exists_result.stat.exists or upgrade
  block:
    - name: Packer - Get HashiCorp gpg
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Packer - Add repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

    - name: Packer - Install/Upgrade
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - packer
