---
- name: RipGrep - Exists
  ansible.builtin.stat:
    path: /usr/local/bin/rg
  register: ripgrep_exists_result

- name: RipGrep - Install
  when: not ripgrep_exists_result.stat.exists or upgrade
  block:
    - name: RipGrep - Install
      ansible.builtin.apt:
        deb: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
        state: present
