---
- name: Sidenoder - Exists
  ansible.builtin.stat:
    path: /usr/local/bin/sidenoder
  register: sidenoder_exists_result

- name: Sidenoder - Install
  when: not sidenoder_exists_result.stat.exists or upgrade
  block:
    - name: Sidenoder - Get latest
      community.general.github_release:
        user: VRPirates
        repo: sidenoder
        action: latest_release
        token: "{{ github_token | default(omit) }}"
      register: sidenoder_latest_version_result

    - name: Sidenoder - Set latest version
      ansible.builtin.set_fact:
        sidenoder_latest_version: "{{ sidenoder_latest_version_result.tag[1:] }}"

    - name: Sidenoder - Install/Upgrade
      ansible.builtin.get_url:
        url: >
          https://github.com/VRPirates/sidenoder/releases/download/{{ sidenoder_latest_version_result.tag }}/
          sidenoder-{{ sidenoder_latest_version_result.tag }}-amd64.AppImage
        dest: /usr/local/bin/sidenoder
        mode: '0755'
