---
- name: Skype - Exists
  ansible.builtin.stat:
    path: /usr/bin/skypeforlinux
  register: skype_result

- name: Skype
  ansible.builtin.apt:
    deb: https://go.skype.com/skypeforlinux-64.deb
  when: not skype_result.stat.exists or upgrade
