---
- name: Team Viewer - Exists
  ansible.builtin.stat:
    path: /usr/bin/teamviewer
  register: teamviewer_result

- name: Team Viewer
  ansible.builtin.apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
  when: not teamviewer_result.stat.exists or upgrade
