---
- name: Teams - Exists
  ansible.builtin.stat:
    path: /usr/bin/teams
  register: teams_exists_result

- name: Microsoft Teams
  ansible.builtin.apt:
    deb: https://go.microsoft.com/fwlink/p/?linkid=2112886
  when: not teams_exists_result.stat.exists or upgrade
