---
- name: Check if HashiCorp GPG key exists
  ansible.builtin.stat:
    path: /etc/apt/keyrings/hashicorp-archive-keyring.gpg
  register: hashicorp_key_exists
  become: true

- name: Download HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp.gpg
    mode: '0644'
    checksum: sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029
  become: true
  when: not hashicorp_key_exists.stat.exists

- name: Convert and import HashiCorp GPG key
  ansible.builtin.shell: |
    gpg --dearmor -o /etc/apt/keyrings/hashicorp-archive-keyring.gpg /tmp/hashicorp.gpg
    chmod 644 /etc/apt/keyrings/hashicorp-archive-keyring.gpg
    rm -f /tmp/hashicorp.gpg
  become: true
  when: not hashicorp_key_exists.stat.exists
  changed_when: true

- name: Add terraform repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.gpg]
      https://apt.releases.hashicorp.com
      {{ ansible_distribution_release }} main
    state: present
  become: true

- name: Terraform - Install
  ansible.builtin.apt:
    pkg:
      - terraform
  become: true
