---
- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: tmp
  register: tmpdir

- name: Warp - Exists
  ansible.builtin.stat:
    path: /usr/bin/warp
  register: warp_result

- name: Install Warp-terminal
  ansible.builtin.apt:
    deb: https://app.warp.dev/get_warp?package=deb
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and (not warp_result.stat.exists or upgrade)

- name: Download and install warp-terminal and (not warp_result.stat.exists or upgrade)
  when: ansible_distribution == 'Archlinux'
  block:
    - name: Download Warp-terminal
      ansible.builtin.get_url:
        url: "{{ sysinit_warp_url }}"
        dest: "{{ tmpdir.path }}/warp-termnal.pkg.tar.zst"
        mode: "0644"
        decompress: false

    - name: Install Warp-terminal
      ansible.builtin.shell: |
        pacman -U --noconfirm  {{ tmpdir.path }}/warp-termnal.pkg.tar.zst
      register: warp_install_result
      changed_when: warp_install_result.rc != 0

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ tmpdir.path }}"
    state: "absent"
