---
sysinit_packages:
  - clang
  - docker
  - docker-buildx
  - flameshot
  - gnome-keyring
  - libxcrypt-compat
  - seahorse

sysinit_aur_packages:
  - aws-session-manager-plugin
  - 1password
  - dropbox
  - slack-desktop

sysinit_tools:
  - mise
