---
- name: Display system info
  ansible.builtin.debug:
    msg:
      - "User: {{ lookup('env', 'USER') }}"
      - "Home: {{ lookup('env', 'HOME') }}"
      - "System: {{ ansible_system }}"
      - "Architecture: {{ ansible_userspace_architecture }}"
      - "Distribution: {{ ansible_distribution }}"
      - "Release: {{ ansible_distribution_release }}"
      - "Sysinit: {{ sysinit_var }}"

- name: Combine tools lists
  ansible.builtin.set_fact:
    sysinit_combined_tools: "{{ (tools | default('') | split(',')) | select('match', '.+') | list + (sysinit_tools | default([])) }}"

- name: Load variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: Install system packages
  ansible.builtin.package:
    name: "{{ sysinit_packages }}"
    state: present

- name: Install community or private packages
  ansible.builtin.include_tasks: "apt.yml"
  loop: "{{ sysinit_custom_apt_packages | default([]) }}"
  when: ansible_distribution == 'Debian'

- name: Install tools
  ansible.builtin.include_tasks: "tools/{{ item }}.yml"
  loop: "{{ combined_tools | default([]) }}"
  when: combined_tools is defined and combined_tools | length > 0

- name: Configure Reach local development
  ansible.builtin.include_tasks: "reach/main.yml"
