---
sysinit_packages:
  - gcc
  - make
  - stow
  - unzip
  - xclip
  - xsel
  - zip

sysinit_sys_tools:
  - mise

sysinit_mise_plugins:
  - 1password-cli
  - amazon-ecr-credential-helper
  - awscli
  - aws-vault
  - bat
  - direnv
  - eksctl
  - eza
  - fd
  - fzf
  - github-cli
  - git-worktree-wrapper
  - golang
  - granted
  - jq
  - k9s
  - kubectl
  - kubectx
  - kubens
  - minikube
  - mkcert
  - neovim
  - node
  - packer
  - pre-commit
  - python
  - rclone
  - ripgrep
  - starship
  - task
  - terraform
  - terragrunt
  - usage
#  - tmux
  - uv
  - zellij

sysinit_mise_custom_plugins:
  - {
    plugin: "git-worktree-wrapper",
    src: "https://github.com/kedwards/asdf-git-worktree-wrapper.git",
  }
