---
sysinit_debug: false
sysinit_force_update: false

sysinit_packages:
  - gcc
  - make
  - stow
  - unzip
  - xclip
  - xsel
  - zip

sysinit_sys_tools:
  - mise

sysinit_mise_plugins:
  - 1password-cli
  - amazon-ecr-credential-helper
  - awscli
  - bat
  - direnv
  - eza
  - fd
  - fzf
  - github-cli
  - git-worktree-wrapper
  - golang
  - granted
  - jq
  - neovim
  - node
  - pre-commit
  - python
  - rclone
  - ripgrep
  - starship
  - task
  - usage
  - uv
  - zellij

sysinit_mise_custom_plugins:
  - {
    plugin: "git-worktree-wrapper",
    src: "https://github.com/kedwards/asdf-git-worktree-wrapper.git",
  }
