---
galaxy_info:
  author: kedwards
  description: System initialization and configuration role
  license: MIT
  min_ansible_version: "2.9"
  
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - system
    - configuration
    - initialization
    - setup

dependencies: []
