---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    environment:
      HOME: /root
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
# Temporarily disable CentOS testing due to Python compatibility issues
  # - name: centos-instance
  #   image: geerlingguy/docker-centos8-ansible:latest
  #   pre_build_image: true
  #   privileged: true
  #   environment:
  #     HOME: /root
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   capabilities:
  #     - SYS_ADMIN
provisioner:
  name: ansible
  config_options:
    defaults:
      host_key_checking: false
    ssh_connection:
      pipelining: true
  inventory:
    host_vars:
      ubuntu-instance:
        ansible_user: root
        withreach_dir: /opt/withreach
        dev_hosts: ["test.local", "api.test.local"]
        hosts_marker: "# Test Development"
      centos-instance:
        ansible_user: root
        withreach_dir: /opt/withreach
        dev_hosts: ["test.local", "api.test.local"]
        hosts_marker: "# Test Development"
verifier:
  name: testinfra
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
