---
- name: Configure system timezone
  community.general.timezone:
    name: "{{ sysinit_timezone | default('UTC') }}"
  when: sysinit_timezone is defined

- name: Configure system locale
  when: ansible_distribution in ['Debian', 'Ubuntu']
  block:
    - name: Configure system locale
      ansible.builtin.package:
        name: locales
        state: present

    - name: Configure system locale
      community.general.locale_gen:
        name: "{{ locale_item }}"
        state: present
      loop: "{{ sysinit_locales | default(['en_US.UTF-8']) }}"
      loop_control:
        loop_var: locale_item

- name: Add local development hosts
  become: true
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {{ sysinit_reach_hosts_marker }}
      {% for host in sysinit_reach_dev_hosts %}
      127.0.0.1 {{ host }}
      {% endfor %}
    marker: "{{ sysinit_reach_hosts_marker }} {mark}"
    create: false
    backup: "{{ sysinit_reach_hosts_backup }}"
  when: sysinit_var | default('') != 'molecule_converge'
  notify: validate hosts
  tags:
    - reach
    - reach-host
    - hosts
    - network
