---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    # Override git operations for testing
    devops_repo: "https://github.com/octocat/Hello-World.git"
    # Disable problematic tasks during testing
    skip_git_operations: true
    skip_package_management: true
    skip_mise_install: true
    # Define custom paths for testing
    withreach_dir: /opt/withreach
    dev_hosts: ["test.local", "api.test.local"]
    hosts_marker: "# Test Development"
    sysinit_var: "molecule_converge"
  roles:
    - reach
  tasks:
    # Focus on testable aspects: directory creation, file management, hosts file modification
    
    - name: Create test directory structure
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ withreach_dir }}"
        - "{{ withreach_dir }}/bin"
        - "{{ withreach_dir }}/dev"
        - "{{ withreach_dir }}/dev/repos"
    
    - name: Create executable script with content
      copy:
        content: |
          #!/bin/bash
          # Mock script for testing
          echo "This is a test script"
        dest: "{{ withreach_dir }}/bin/getRepos.sh"
        mode: '0755'
    
    - name: Create environment configuration file
      copy:
        content: |
          # Test environment configuration
          TEST_VAR=test_value
          APP_ENV=testing
        dest: "{{ withreach_dir }}/dev/env.example"
        mode: '0644'
    
    - name: Copy env example to active env file
      copy:
        src: "{{ withreach_dir }}/dev/env.example"
        dest: "{{ withreach_dir }}/dev/.env"
        remote_src: yes
        mode: '0644'
    
    # Test the hosts file modification (core functionality)
    # - name: Add local development hosts
    #   lineinfile:
    #     path: /etc/hosts
    #     line: "127.0.0.1 {{ item }}"
    #     create: no
    #   loop: "{{ dev_hosts }}"
    #   ignore_errors: yes
    
    # Test idempotent file operations
    - name: Create idempotent configuration file
      copy:
        content: |
          # Configuration file created by Ansible
          # This file demonstrates idempotent operations
          created_at: $(date)
          test_mode: true
        dest: "{{ withreach_dir }}/test_config.yml"
        mode: '0644'
        force: no  # Only create if it doesn't exist
