---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: sysinit-ubuntu-22
    image: ubuntu
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: sleep infinity
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../roles
  log: true
  inventory:
    host_vars:
      sysinit-ubuntu-22:
        ansible_user: root
        withreach_dir: /opt/withreach
        dev_hosts: ["test.local", "api.test.local"]
        hosts_marker: "# Test Development"
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      host_key_checking: false
    ssh_connection:
      pipelining: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
