---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: sysinit-ubuntu-22
    image: ubuntu
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: sleep infinity
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  inventory:
    host_vars:
      sysinit-ubuntu-22:
        ansible_user: root
        github_token: ""
        upgrade: false
        tools:
          - starship
          - aws-vault
          - terraform
          - docker
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      roles_path: /home/kedwards/dev/sysinit/feature.cleanup/roles
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
