---
- name: Create sudoers rule for hosts file modification
  ansible.builtin.copy:
    content: |
      # Allow user to modify /etc/hosts without password
      {{ ansible_user | default(ansible_user_id) }} ALL=(ALL) NOPASSWD: /usr/bin/tee -a /etc/hosts
    dest: /etc/sudoers.d/hosts-access
    owner: root
    group: root
    mode: '0440'
    validate: 'visudo -cf %s'
  become: true
