---
- name: Configure system timezone
  ansible.builtin.timezone:
    name: "{{ sysinit_timezone | default('UTC') }}"
  when: sysinit_timezone is defined

- name: Configure system locale
  ansible.builtin.package:
    name: locales
    state: present

- name: Configure system locale
  ansible.builtin.locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ sysinit_locales | default(['en_US.UTF-8']) }}"
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Add local development hosts
  become: yes
  blockinfile:
    path: /etc/hosts
    block: |
      {{ sysinit_hosts_marker }}
      {% for host in sysinit_dev_hosts %}
      127.0.0.1 {{ host }}
      {% endfor %}
    marker: "{{ sysinit_hosts_marker }} {mark}"
    create: no
  when: sysinit_var | default('') != 'molecule_converge'
