---
# - name: Create user profile directory
#   ansible.builtin.file:
#     path: "/home/{{ ansible_env.USER | default(ansible_user_id) }}/.profile.d"
#     state: directory
#     mode: '0700'

# - name: Create other necessary directories
#   ansible.builtin.file:
#     path: "/home/{{ ansible_env.USER | default(ansible_user_id) }}/{{ item }}"
#     state: directory
#     owner: "{{ ansible_env.USER | default(ansible_user_id) }}"
#     group: "{{ ansible_env.USER | default(ansible_user_id) }}"
#     mode: '0755'
#   loop:
#     - .aws
#     - .config
#     - .docker
#     - .granted
#     - .ssh

# - name: Deploy profile.d files from skel templates
#   ansible.builtin.template:
#     src: "skel/.profile.d/{{ item }}"
#     dest: "/home/{{ ansible_env.USER | default(ansible_user_id) }}/.profile.d/{{ item }}"
#     owner: "{{ ansible_env.USER | default(ansible_user_id) }}"
#     group: "{{ ansible_env.USER | default(ansible_user_id) }}"
#     mode: '0644'
#   loop:
#     - _init
#     - aliases
#     - history
#     - reach

# - name: Copy aws profile file as-is (no templating)
#   ansible.builtin.copy:
#     src: "skel/.profile.d/aws"
#     dest: "/home/{{ ansible_env.USER | default(ansible_user_id) }}/.profile.d/aws"
#     owner: "{{ ansible_env.USER | default(ansible_user_id) }}"
#     group: "{{ ansible_env.USER | default(ansible_user_id) }}"
#     mode: '0644'

# - name: Deploy user configuration files from skel templates
#   ansible.builtin.template:
#     src: "skel/{{ item }}"
#     dest: "/home/{{ ansible_env.USER | default(ansible_user_id) }}/{{ item }}"
#     owner: "{{ ansible_env.USER | default(ansible_user_id) }}"
#     group: "{{ ansible_env.USER | default(ansible_user_id) }}"
#     mode: '0644'
#   loop:
#     - .profile
#     - .zprofile
#     - .psqlrc
#     - .gitconfig
#     - .aws/config
#     - .config/starship.toml
#     - .granted/config
#     - .ssh/config
#     - .docker/config.json

# - name: Ensure proper ownership of .profile.d directory and contents
#   ansible.builtin.file:
#     path: "/home/{{ ansible_env.USER | default(ansible_user_id) }}/.profile.d"
#     owner: "{{ ansible_env.USER | default(ansible_user_id) }}"
#     group: "{{ ansible_env.USER | default(ansible_user_id) }}"
#     recurse: yes
#     state: directory
